// <auto-generated />
using JogoDaForca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoDaForca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JogoDaForca.Models.DiscoveryChar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<int>("ForcaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForcaId");

                    b.ToTable("DiscoveryChars");
                });

            modelBuilder.Entity("JogoDaForca.Models.Forca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Done")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("SecretWord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Forcas");
                });

            modelBuilder.Entity("JogoDaForca.Models.DiscoveryChar", b =>
                {
                    b.HasOne("JogoDaForca.Models.Forca", "Forca")
                        .WithMany("DicoveryChars")
                        .HasForeignKey("ForcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forca");
                });

            modelBuilder.Entity("JogoDaForca.Models.Forca", b =>
                {
                    b.Navigation("DicoveryChars");
                });
#pragma warning restore 612, 618
        }
    }
}
